package HALUT;

import ACCOUNT.ACCOUNT;
import KONEKSI.konek;
import static KONEKSI.konek.conn;
import LAPORAN.LAPORAN;
import MEMBER.MEMBER;
import PEMBELIAN.PEMBELIAN;
import PENJUALAN.PENJUALAN;
import STOK.STOK;
import STOK.STOK;
import SUPPLIER.SUPPLIER;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author devipermata
 */
public class HALAMANUTAMA extends javax.swing.JFrame {
private Connection conn;
    
        
    
    public HALAMANUTAMA() {
       
        initComponents();
        conn = konek.getConnection();

    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnpenjualan = new javax.swing.JButton();
        btnstok = new javax.swing.JButton();
        btnpembelian = new javax.swing.JButton();
        btnlaporan = new javax.swing.JButton();
        btnsupplier = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btnaccount = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HALUT/beranda.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        btnpenjualan.setText("Penjualan");
        btnpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpenjualanActionPerformed(evt);
            }
        });
        getContentPane().add(btnpenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 290, 50));

        btnstok.setText("Stok");
        btnstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstokActionPerformed(evt);
            }
        });
        getContentPane().add(btnstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 290, 50));

        btnpembelian.setText("Pembelian");
        btnpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpembelianActionPerformed(evt);
            }
        });
        getContentPane().add(btnpembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 300, 50));

        btnlaporan.setText("Laporan");
        btnlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btnlaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 290, 50));

        btnsupplier.setText("Supplier");
        btnsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupplierActionPerformed(evt);
            }
        });
        getContentPane().add(btnsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 300, 60));

        btnkeluar.setText("Keluar");
        btnkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkeluarMouseClicked(evt);
            }
        });
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 280, 50));

        btnaccount.setText("Account");
        btnaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccountActionPerformed(evt);
            }
        });
        getContentPane().add(btnaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 650, 290, 50));

        jButton1.setText("member");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 290, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


                                
    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseClicked
      dispose();
    }//GEN-LAST:event_btnkeluarMouseClicked

    private void btnstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstokActionPerformed
    STOK s = new STOK();
    s.setVisible(true);

Timer timer = new Timer(300, new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        dispose(); // Tutup frame saat ini setelah 300 ms
    }
});
timer.setRepeats(false); // Timer hanya jalan sekali
timer.start();
    }//GEN-LAST:event_btnstokActionPerformed

    private void btnpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpenjualanActionPerformed
      PENJUALAN J = new PENJUALAN();
    J.setVisible(true);

Timer timer = new Timer(300, new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        dispose(); // Tutup frame saat ini setelah 300 ms
    }
});
timer.setRepeats(false); // Timer hanya jalan sekali
timer.start(); 
    }//GEN-LAST:event_btnpenjualanActionPerformed

    private void btnpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpembelianActionPerformed
    PEMBELIAN B = new PEMBELIAN();
    B.setVisible(true);

Timer timer = new Timer(300, new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        dispose(); // Tutup frame saat ini setelah 300 ms
    }
});
timer.setRepeats(false); // Timer hanya jalan sekali
timer.start();
    }//GEN-LAST:event_btnpembelianActionPerformed

    private void btnlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanActionPerformed
      LAPORAN s = new LAPORAN();
    s.setVisible(true);

Timer timer = new Timer(300, new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        dispose(); // Tutup frame saat ini setelah 300 ms
    }
});
timer.setRepeats(false); // Timer hanya jalan sekali
timer.start();
    }//GEN-LAST:event_btnlaporanActionPerformed

    private void btnsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupplierActionPerformed
       SUPPLIER sP = new SUPPLIER();
    sP.setVisible(true);

Timer timer = new Timer(300, new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        dispose(); // Tutup frame saat ini setelah 300 ms
    }
});
timer.setRepeats(false); // Timer hanya jalan sekali
timer.start();
    }//GEN-LAST:event_btnsupplierActionPerformed

    private void btnaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccountActionPerformed
     ACCOUNT AC = new ACCOUNT();
    AC.setVisible(true);

Timer timer = new Timer(300, new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        dispose(); // Tutup frame saat ini setelah 300 ms
    }
});
timer.setRepeats(false); // Timer hanya jalan sekali
timer.start();
    }//GEN-LAST:event_btnaccountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      MEMBER MEM = new MEMBER();
    MEM.setVisible(true);

Timer timer = new Timer(300, new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        dispose(); // Tutup frame saat ini setelah 300 ms
    }
});
timer.setRepeats(false); // Timer hanya jalan sekali
timer.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HALAMANUTAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HALAMANUTAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HALAMANUTAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HALAMANUTAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              new HALAMANUTAMA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaccount;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnlaporan;
    private javax.swing.JButton btnpembelian;
    private javax.swing.JButton btnpenjualan;
    private javax.swing.JButton btnstok;
    private javax.swing.JButton btnsupplier;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
